#Expyriment 0.9.0 (Python 3.6.4), .xpe-file, coding: UTF-8
#date: Fri Aug 03 2018 20:12:27
#sha1: None
#modules: 
#display: size=(1920, 1080), window_mode=False, open_gl=2
#os: uname_result(system='Linux', node='xps', release='4.15.0-29-generic', version='#31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
4725,Stimulus,presented,60
5728,Stimulus,presented,46
11643,Keyboard,received,275,wait
11644,stderr,received,'Traceback (most recent call last):'
11644,stderr,received,'  File "/home/dieter/Dropbox/PythonCourse/22_Experiment_Analysis/Experiment.py", line 46, in <module>'
11644,stderr,received,'    exp.data.add([block.name, trial.id, trial.condition, trial.valence, key, rt])'
11644,stderr,received,"AttributeError: 'NoneType' object has no attribute 'add'"
